# Generated by Django 2.2.5 on 2019-10-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20191009_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='intensity_module',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
